(() => {
  const SOURCE_CATALOG = [
    {
      id: "grupodewhatsapp",
      label: "GrupoDeWhatsApp.com",
      seedUrl: "https://grupodewhatsapp.com/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "gruposwhats",
      label: "GruposWhats.app",
      seedUrl: "https://gruposwhats.app/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "gruposdewhatsappsite",
      label: "GruposDeWhatsApp.site",
      seedUrl: "https://gruposdewhatsapp.site/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "gruposwhatslink",
      label: "grupos.whats.link",
      seedUrl: "https://grupos.whats.link/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "grupax",
      label: "Grupax",
      seedUrl: "https://grupax.com.br/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "gruposbrasil",
      label: "GruposBrasil BR",
      seedUrl: "https://gruposbrasil.com.br/",
      description: "Diretório de grupos de WhatsApp e Telegram.",
      enabledByDefault: true,
    },
    {
      id: "gruposbrasilcom",
      label: "GruposBrasil",
      seedUrl: "https://gruposbrasil.com/",
      description: "Catálogo de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "allgrupos",
      label: "AllGrupos",
      seedUrl: "https://www.allgrupos.com.br/",
      description: "Diretório de grupos de WhatsApp e Telegram.",
      enabledByDefault: true,
    },
    {
      id: "gruposdewhatss",
      label: "GruposDeWhatss.com.br",
      seedUrl: "https://gruposdewhatss.com.br/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "usgruposwats",
      label: "US GruposWats",
      seedUrl: "https://us.gruposwats.com/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "gruposwatscom",
      label: "GruposWats",
      seedUrl: "https://www.gruposwats.com/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "gruposdewhatssapp",
      label: "GruposDeWhatss.app",
      seedUrl: "https://gruposdewhatss.app/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "gruposdezap",
      label: "GruposDeZap",
      seedUrl: "https://gruposdezap.com.br/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "wgrupos",
      label: "WGrupos",
      seedUrl: "https://wgrupos.com/",
      description: "Diretório de grupos de WhatsApp e Telegram.",
      enabledByDefault: true,
    },
    {
      id: "grupostelegram",
      label: "GruposTelegram.net",
      seedUrl: "https://grupostelegram.net/",
      description: "Diretório de grupos de Telegram.",
      enabledByDefault: true,
    },
    {
      id: "telegrupos",
      label: "TeleGrupos",
      seedUrl: "https://telegrupos.com.br/",
      description: "Diretório de grupos de Telegram.",
      enabledByDefault: true,
    },
    {
      id: "wagrupos",
      label: "WAGrupos",
      seedUrl: "https://wagrupos.com.br/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "gruposdewhats",
      label: "GruposDeWhats",
      seedUrl: "https://gruposdewhats.com.br/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "gruposdewhatsappgratis",
      label: "Grupos de WhatsApp Grátis",
      seedUrl: "https://www.gruposdewhatsappgratis.com.br/",
      description: "Diretório de grupos de WhatsApp.",
      enabledByDefault: true,
    },
    {
      id: "prodivulgas",
      label: "ProDivulgas",
      seedUrl: "https://prodivulgas.com/",
      description: "Diretório de grupos de WhatsApp e Telegram.",
      enabledByDefault: true,
    },
    {
      id: "telegruposbr",
      label: "TeleGrupos BR",
      seedUrl: "https://telegruposbr.com/",
      description: "Diretório de grupos e canais de Telegram.",
      enabledByDefault: true,
    },
    {
      id: "telegruposvip",
      label: "TeleGrupos VIP",
      seedUrl: "https://telegruposvip.com.br/",
      description: "Diretório de grupos e canais de Telegram.",
      enabledByDefault: true,
    },
    {
      id: "grupoporno",
      label: "GrupoPorno.com",
      seedUrl: "https://grupoporno.com/",
      description: "Diretório adulto (+18) de grupos.",
      enabledByDefault: false,
      adultOnly: true,
    },
    {
      id: "gruposputariatelegram",
      label: "GruposPutariaTelegram.com",
      seedUrl: "https://gruposputariatelegram.com/",
      description: "Diretório adulto (+18) de grupos de Telegram.",
      enabledByDefault: false,
      adultOnly: true,
    },
  ];

  globalThis.FerramentaConsultaSources = {
    SOURCE_CATALOG,
  };
})();
