import {
  CatalogCompany,
  CatalogItem,
  FilterDefinition,
  SegmentConfig,
} from "./catalog-types";

const select = (label: string, value: string) => ({ label, value });

export const companies: CatalogCompany[] = [
  {
    slug: "imobiliaria-horizonte",
    name: "Imobiliária Horizonte",
    segment: "imoveis",
    city: "Maringá",
    description: "Catálogo imobiliário com imóveis de compra e aluguel, focado em filtros reais.",
    accent: "#74f1c7",
    tagline: "Busca precisa para imóveis prontos para visita.",
  },
  {
    slug: "prime-motors",
    name: "Prime Motors",
    segment: "veiculos",
    city: "Londrina",
    description: "Estoque demo de veículos com filtros de ano, carroceria, combustível e km.",
    accent: "#8da6ff",
    tagline: "Estoque automotivo com leitura estruturada.",
  },
  {
    slug: "urban-store",
    name: "Urban Store",
    segment: "ecommerce",
    city: "Curitiba",
    description: "Produtos e variações pensados para testar disponibilidade, cor e tamanho.",
    accent: "#ffb86b",
    tagline: "Variações e estoque sem inventar disponibilidade.",
  },
  {
    slug: "pizza-bella",
    name: "Pizza Bella",
    segment: "food",
    city: "Maringá",
    description: "Cardápio demo com tamanhos, adicionais, restrições e itens servidos por pessoa.",
    accent: "#ff6f91",
    tagline: "Menu inteligente com filtros e montagem de pedidos.",
  },
];

const propertyFilters: FilterDefinition[] = [
  { key: "q", label: "Buscar", type: "text", placeholder: "Apartamento, bairro, cidade..." },
  {
    key: "tipo",
    label: "Tipo",
    type: "select",
    options: [
      select("Todos", ""),
      select("Apartamento", "apartamento"),
      select("Casa", "casa"),
      select("Terreno", "terreno"),
      select("Comercial", "comercial"),
      select("Chácara", "chacara"),
      select("Studio", "studio"),
      select("Cobertura", "cobertura"),
    ],
  },
  {
    key: "finalidade",
    label: "Finalidade",
    type: "select",
    options: [select("Todas", ""), select("Venda", "venda"), select("Aluguel", "aluguel")],
  },
  { key: "cidade", label: "Cidade", type: "text", placeholder: "Maringá" },
  { key: "bairro", label: "Bairro", type: "text", placeholder: "Zona 07" },
  { key: "quartos_min", label: "Quartos mín.", type: "number", step: 1 },
  { key: "preco_max", label: "Preço máx.", type: "number", step: 1000 },
  { key: "mobiliado", label: "Mobiliado", type: "boolean" },
  { key: "financiamento", label: "Financiamento", type: "boolean" },
  { key: "pets", label: "Aceita pets", type: "boolean" },
];

const vehicleFilters: FilterDefinition[] = [
  { key: "q", label: "Buscar", type: "text", placeholder: "Marca, modelo, versão..." },
  { key: "marca", label: "Marca", type: "text", placeholder: "Toyota" },
  { key: "modelo", label: "Modelo", type: "text", placeholder: "Corolla" },
  { key: "carroceria", label: "Carroceria", type: "select", options: [
    select("Todas", ""),
    select("Hatch", "hatch"),
    select("Sedan", "sedan"),
    select("SUV", "suv"),
    select("Picape", "picape"),
    select("Utilitário", "utilitario"),
  ] },
  { key: "cambio", label: "Câmbio", type: "select", options: [
    select("Todos", ""),
    select("Manual", "manual"),
    select("Automático", "automatico"),
    select("CVT", "cvt"),
  ] },
  { key: "combustivel", label: "Combustível", type: "select", options: [
    select("Todos", ""),
    select("Flex", "flex"),
    select("Gasolina", "gasolina"),
    select("Diesel", "diesel"),
    select("Elétrico", "eletrico"),
    select("Híbrido", "hibrido"),
  ] },
  { key: "ano_min", label: "Ano mín.", type: "number", step: 1 },
  { key: "preco_max", label: "Preço máx.", type: "number", step: 1000 },
  { key: "km_max", label: "KM máx.", type: "number", step: 1000 },
  { key: "troca", label: "Aceita troca", type: "boolean" },
  { key: "financiamento", label: "Financiamento", type: "boolean" },
];

const productFilters: FilterDefinition[] = [
  { key: "q", label: "Buscar", type: "text", placeholder: "Produto, marca, material..." },
  { key: "categoria", label: "Categoria", type: "text", placeholder: "Moda, eletrônicos..." },
  { key: "cor", label: "Cor", type: "text", placeholder: "Preto" },
  { key: "tamanho", label: "Tamanho", type: "text", placeholder: "M" },
  { key: "variacao", label: "Variação", type: "text", placeholder: "Preto G, azul..." },
  { key: "marca", label: "Marca", type: "text", placeholder: "Urban Studio" },
  { key: "subcategoria", label: "Subcategoria", type: "text", placeholder: "Camisetas" },
  { key: "preco_max", label: "Preço máx.", type: "number", step: 1 },
  { key: "estoque_min", label: "Estoque mín.", type: "number", step: 1 },
  { key: "sku", label: "SKU", type: "text", placeholder: "UST-..." },
];

const foodFilters: FilterDefinition[] = [
  { key: "q", label: "Buscar", type: "text", placeholder: "Pizza, lanche, sobremesa..." },
  { key: "categoria", label: "Categoria", type: "text", placeholder: "Pizzas, burgers..." },
  { key: "serve_min", label: "Serve mín.", type: "number", step: 1 },
  { key: "sem", label: "Sem ingrediente", type: "text", placeholder: "cebola, lactose..." },
  { key: "adicional", label: "Adicional", type: "text", placeholder: "catupiry..." },
  { key: "alergeno", label: "Alérgeno", type: "text", placeholder: "glúten..." },
  { key: "preco_max", label: "Preço máx.", type: "number", step: 1 },
];

export const segments: SegmentConfig[] = [
  {
    key: "imoveis",
    label: "Imóveis",
    shortLabel: "Imóveis",
    publicPath: "/catalogos/imoveis",
    apiPath: "/api/catalogos/imoveis",
    description: "Catálogo com filtros de compra e aluguel, pronto para simular busca imobiliária.",
    defaultCompanySlug: "imobiliaria-horizonte",
    filterDefinitions: propertyFilters,
    queryExamples: [
      "Quero um apartamento em Maringá com 3 quartos.",
      "Tem casa até 800 mil?",
      "Algo financiável na Zona 07?",
    ],
  },
  {
    key: "veiculos",
    label: "Veículos",
    shortLabel: "Veículos",
    publicPath: "/catalogos/veiculos",
    apiPath: "/api/catalogos/veiculos",
    description: "Estoque automotivo com leitura de marca, ano, KM, carroceria e câmbio.",
    defaultCompanySlug: "prime-motors",
    filterDefinitions: vehicleFilters,
    queryExamples: [
      "Quero um SUV automático até 130 mil.",
      "Tem Corolla 2024 com baixa quilometragem?",
      "Procuro picape diesel com troca.",
    ],
  },
  {
    key: "ecommerce",
    label: "E-commerce",
    shortLabel: "E-commerce",
    publicPath: "/catalogos/ecommerce",
    apiPath: "/api/catalogos/ecommerce",
    description: "Produtos com variantes, estoque e disponibilidade por cor e tamanho.",
    defaultCompanySlug: "urban-store",
    filterDefinitions: productFilters,
    queryExamples: [
      "Tem preta tamanho G?",
      "Quero um notebook até 5 mil.",
      "Mostre camisetas com estoque.",
    ],
  },
  {
    key: "food",
    label: "Food",
    shortLabel: "Food",
    publicPath: "/catalogos/food",
    apiPath: "/api/catalogos/food",
    description: "Cardápio com tamanhos, adicionais, ingredientes e restrições alimentares.",
    defaultCompanySlug: "pizza-bella",
    filterDefinitions: foodFilters,
    queryExamples: [
      "Tem pizza sem cebola para 4 pessoas?",
      "Quero um burger com bacon e batata.",
      "Quais pratos servem duas pessoas?",
    ],
  },
];

const propertyItems: CatalogItem[] = [
  {
    id: "imo-001",
    slug: "residencial-aurora",
    name: "Residencial Aurora",
    companySlug: "imobiliaria-horizonte",
    companyName: "Imobiliária Horizonte",
    segment: "imoveis",
    status: "ativo",
    price: 680000,
    description: "Apartamento amplo próximo ao centro, com sacada gourmet e ótima ventilação.",
    highlights: ["3 quartos", "1 suíte", "2 vagas"],
    galleryTone: "linear-gradient(135deg, #74f1c7, #214f64)",
    featured: true,
    details: {
      type: "apartamento",
      purpose: "venda",
      city: "Maringá",
      neighborhood: "Zona 07",
      address: "Rua Pioneiro José Laurindo, 128",
      bedrooms: 3,
      suites: 1,
      bathrooms: 2,
      parking: 2,
      areaUseful: 112,
      areaTotal: 145,
      furnished: false,
      financing: true,
      pets: true,
      condominium: 640,
      iptu: 110,
      features: ["sacada gourmet", "elevador", "churrasqueira", "salão de festas"],
    },
  },
  {
    id: "imo-002",
    slug: "casa-jardim-imperial",
    name: "Casa Jardim Imperial",
    companySlug: "imobiliaria-horizonte",
    companyName: "Imobiliária Horizonte",
    segment: "imoveis",
    status: "ativo",
    price: 1240000,
    description: "Casa de alto padrão com quintal amplo e espaço para home office.",
    highlights: ["4 quartos", "2 suítes", "3 vagas"],
    galleryTone: "linear-gradient(135deg, #8da6ff, #26355f)",
    details: {
      type: "casa",
      purpose: "venda",
      city: "Cianorte",
      neighborhood: "Jardim Imperial",
      address: "Alameda das Acácias, 90",
      bedrooms: 4,
      suites: 2,
      bathrooms: 4,
      parking: 3,
      areaUseful: 240,
      areaTotal: 360,
      furnished: true,
      financing: true,
      pets: true,
      condominium: 0,
      iptu: 180,
      features: ["piscina", "quintal", "lavabo", "energia solar"],
    },
  },
  {
    id: "imo-003",
    slug: "edificio-horizon-park",
    name: "Edifício Horizon Park",
    companySlug: "imobiliaria-horizonte",
    companyName: "Imobiliária Horizonte",
    segment: "imoveis",
    status: "ativo",
    price: 3200,
    description: "Apartamento para locação com vista aberta e infraestrutura completa.",
    highlights: ["2 quartos", "1 suíte", "locação"],
    galleryTone: "linear-gradient(135deg, #ffb86b, #5a3a17)",
    details: {
      type: "apartamento",
      purpose: "aluguel",
      city: "Londrina",
      neighborhood: "Gleba Palhano",
      address: "Rua Chile, 520",
      bedrooms: 2,
      suites: 1,
      bathrooms: 2,
      parking: 1,
      areaUseful: 84,
      areaTotal: 108,
      furnished: true,
      financing: false,
      pets: false,
      condominium: 430,
      iptu: 95,
      features: ["academia", "piscina", "portaria 24h", "coworking"],
    },
  },
  {
    id: "imo-004",
    slug: "terreno-alto-da-colina",
    name: "Terreno Alto da Colina",
    companySlug: "imobiliaria-horizonte",
    companyName: "Imobiliária Horizonte",
    segment: "imoveis",
    status: "ativo",
    price: 290000,
    description: "Lote plano em rua tranquila, ideal para projeto residencial contemporâneo.",
    highlights: ["360 m²", "plano", "pronto para construir"],
    galleryTone: "linear-gradient(135deg, #74f1c7, #163126)",
    details: {
      type: "terreno",
      purpose: "venda",
      city: "Maringá",
      neighborhood: "Jardim Colina Verde",
      address: "Rua Projetada, lote 18",
      bedrooms: 0,
      suites: 0,
      bathrooms: 0,
      parking: 0,
      areaUseful: 360,
      areaTotal: 360,
      furnished: false,
      financing: true,
      pets: false,
      condominium: 0,
      iptu: 60,
      features: ["plano", "esquina", "murado", "documentação ok"],
    },
  },
  {
    id: "imo-005",
    slug: "sala-comercial-centro-empresarial",
    name: "Sala Comercial Centro Empresarial",
    companySlug: "imobiliaria-horizonte",
    companyName: "Imobiliária Horizonte",
    segment: "imoveis",
    status: "ativo",
    price: 540000,
    description: "Sala ampla para escritório ou clínica, em edifício corporativo estratégico.",
    highlights: ["78 m²", "1 vaga", "centro"],
    galleryTone: "linear-gradient(135deg, #8da6ff, #15213a)",
    details: {
      type: "comercial",
      purpose: "venda",
      city: "Maringá",
      neighborhood: "Centro",
      address: "Av. Paraná, 640",
      bedrooms: 0,
      suites: 0,
      bathrooms: 2,
      parking: 1,
      areaUseful: 78,
      areaTotal: 92,
      furnished: true,
      financing: true,
      pets: false,
      condominium: 710,
      iptu: 130,
      features: ["ar central", "recepção", "elevador", "cabeamento"],
    },
  },
  {
    id: "imo-006",
    slug: "casa-duo-bosque",
    name: "Casa Duo Bosque",
    companySlug: "imobiliaria-horizonte",
    companyName: "Imobiliária Horizonte",
    segment: "imoveis",
    status: "ativo",
    price: 890000,
    description: "Casa térrea com planta funcional e quintal generoso em bairro valorizado.",
    highlights: ["3 quartos", "1 suíte", "quintal"],
    galleryTone: "linear-gradient(135deg, #ff6f91, #4b1d2b)",
    details: {
      type: "casa",
      purpose: "venda",
      city: "Campo Mourão",
      neighborhood: "Bosque das Flores",
      address: "Rua das Araucárias, 12",
      bedrooms: 3,
      suites: 1,
      bathrooms: 3,
      parking: 2,
      areaUseful: 150,
      areaTotal: 240,
      furnished: false,
      financing: true,
      pets: true,
      condominium: 0,
      iptu: 85,
      features: ["quintal", "área gourmet", "portão eletrônico", "depósito"],
    },
  },
  {
    id: "imo-007",
    slug: "cobertura-atlantica",
    name: "Cobertura Atlântica",
    companySlug: "imobiliaria-horizonte",
    companyName: "Imobiliária Horizonte",
    segment: "imoveis",
    status: "ativo",
    price: 1890000,
    description: "Cobertura sofisticada com vista aberta, piscina privativa e acabamento premium.",
    highlights: ["4 quartos", "3 suítes", "piscina privativa"],
    galleryTone: "linear-gradient(135deg, #ffb86b, #7b4414)",
    details: {
      type: "cobertura",
      purpose: "venda",
      city: "Paranavaí",
      neighborhood: "Centro",
      address: "Rua Marechal Cândido Rondon, 410",
      bedrooms: 4,
      suites: 3,
      bathrooms: 5,
      parking: 3,
      areaUseful: 210,
      areaTotal: 286,
      furnished: true,
      financing: false,
      pets: true,
      condominium: 1350,
      iptu: 220,
      features: ["piscina privativa", "terraço", "churrasqueira", "vista panorâmica"],
    },
  },
  {
    id: "imo-008",
    slug: "studio-city-pulse",
    name: "Studio City Pulse",
    companySlug: "imobiliaria-horizonte",
    companyName: "Imobiliária Horizonte",
    segment: "imoveis",
    status: "ativo",
    price: 2100,
    description: "Studio compacto, mobiliado e perfeito para locação curta ou executiva.",
    highlights: ["mobiliado", "1 quarto", "área central"],
    galleryTone: "linear-gradient(135deg, #74f1c7, #1a2734)",
    details: {
      type: "studio",
      purpose: "aluguel",
      city: "Maringá",
      neighborhood: "Zona 01",
      address: "Rua Neo Alves Martins, 55",
      bedrooms: 1,
      suites: 1,
      bathrooms: 1,
      parking: 0,
      areaUseful: 38,
      areaTotal: 42,
      furnished: true,
      financing: false,
      pets: false,
      condominium: 290,
      iptu: 46,
      features: ["mobiliado", "lavanderia compartilhada", "wifi", "portaria digital"],
    },
  },
  {
    id: "imo-009",
    slug: "chacara-recanto-verde",
    name: "Chácara Recanto Verde",
    companySlug: "imobiliaria-horizonte",
    companyName: "Imobiliária Horizonte",
    segment: "imoveis",
    status: "ativo",
    price: 1540000,
    description: "Chácara com lazer completo e ampla área verde para descanso ou eventos.",
    highlights: ["2.000 m²", "lazer completo", "aceita pets"],
    galleryTone: "linear-gradient(135deg, #6fca87, #173524)",
    details: {
      type: "chacara",
      purpose: "venda",
      city: "Sarandi",
      neighborhood: "Zona Rural",
      address: "Estrada Rural, km 6",
      bedrooms: 5,
      suites: 2,
      bathrooms: 4,
      parking: 6,
      areaUseful: 320,
      areaTotal: 2000,
      furnished: true,
      financing: false,
      pets: true,
      condominium: 0,
      iptu: 70,
      features: ["piscina", "salão de festas", "pomar", "área de churrasco"],
    },
  },
  {
    id: "imo-010",
    slug: "apartamento-lume",
    name: "Apartamento Lume",
    companySlug: "imobiliaria-horizonte",
    companyName: "Imobiliária Horizonte",
    segment: "imoveis",
    status: "ativo",
    price: 495000,
    description: "Apartamento moderno com varanda integrada e layout funcional.",
    highlights: ["2 quartos", "1 suíte", "1 vaga"],
    galleryTone: "linear-gradient(135deg, #8da6ff, #25376f)",
    details: {
      type: "apartamento",
      purpose: "venda",
      city: "Apucarana",
      neighborhood: "Vila Nova",
      address: "Rua Rio Branco, 742",
      bedrooms: 2,
      suites: 1,
      bathrooms: 2,
      parking: 1,
      areaUseful: 76,
      areaTotal: 98,
      furnished: false,
      financing: true,
      pets: true,
      condominium: 520,
      iptu: 92,
      features: ["varanda", "cozinha planejada", "elevador", "salão de jogos"],
    },
  },
];

const vehicleItems: CatalogItem[] = [
  {
    id: "veh-001",
    slug: "corolla-xei-2024",
    name: "Corolla XEi 2024",
    companySlug: "prime-motors",
    companyName: "Prime Motors",
    segment: "veiculos",
    status: "ativo",
    price: 149900,
    description: "Sedan completo, confortável e com baixa quilometragem.",
    highlights: ["automático", "flex", "1 dono"],
    galleryTone: "linear-gradient(135deg, #8da6ff, #1f2e56)",
    featured: true,
    details: {
      brand: "Toyota",
      model: "Corolla",
      version: "XEi",
      year: 2024,
      modelYear: 2024,
      mileage: 9200,
      gearbox: "automatico",
      fuel: "flex",
      body: "sedan",
      color: "Prata",
      doors: 4,
      exchange: true,
      financing: true,
      warranty: true,
      oneOwner: true,
      blindado: false,
      features: ["multimídia", "câmera de ré", "piloto automático", "controle de faixa"],
    },
  },
  {
    id: "veh-002",
    slug: "toro-freedom-2023",
    name: "Toro Freedom 2023",
    companySlug: "prime-motors",
    companyName: "Prime Motors",
    segment: "veiculos",
    status: "ativo",
    price: 127900,
    description: "Picape versátil com ótimo espaço de cabine e caçamba funcional.",
    highlights: ["picape", "diesel", "automático"],
    galleryTone: "linear-gradient(135deg, #ffb86b, #613d1a)",
    details: {
      brand: "Fiat",
      model: "Toro",
      version: "Freedom",
      year: 2023,
      modelYear: 2023,
      mileage: 37450,
      gearbox: "automatico",
      fuel: "diesel",
      body: "picape",
      color: "Branco",
      doors: 4,
      exchange: true,
      financing: true,
      warranty: false,
      oneOwner: false,
      blindado: false,
      features: ["capota marítima", "ar digital", "4x4", "bancos em couro"],
    },
  },
  {
    id: "veh-003",
    slug: "creta-platinum-2022",
    name: "Creta Platinum 2022",
    companySlug: "prime-motors",
    companyName: "Prime Motors",
    segment: "veiculos",
    status: "ativo",
    price: 123900,
    description: "SUV urbano com pacote premium e condução confortável.",
    highlights: ["SUV", "automático", "multimídia"],
    galleryTone: "linear-gradient(135deg, #74f1c7, #1d4636)",
    details: {
      brand: "Hyundai",
      model: "Creta",
      version: "Platinum",
      year: 2022,
      modelYear: 2022,
      mileage: 28100,
      gearbox: "automatico",
      fuel: "flex",
      body: "suv",
      color: "Cinza",
      doors: 4,
      exchange: false,
      financing: true,
      warranty: false,
      oneOwner: true,
      blindado: false,
      features: ["teto solar", "bancos em couro", "assistente de partida", "chave presencial"],
    },
  },
  {
    id: "veh-004",
    slug: "s10-ltz-2021",
    name: "S10 LTZ 2021",
    companySlug: "prime-motors",
    companyName: "Prime Motors",
    segment: "veiculos",
    status: "ativo",
    price: 169900,
    description: "Picape forte para trabalho e estrada, com cabine dupla.",
    highlights: ["4x4", "diesel", "cabine dupla"],
    galleryTone: "linear-gradient(135deg, #ff6f91, #4e1f32)",
    details: {
      brand: "Chevrolet",
      model: "S10",
      version: "LTZ",
      year: 2021,
      modelYear: 2021,
      mileage: 61240,
      gearbox: "automatico",
      fuel: "diesel",
      body: "picape",
      color: "Preto",
      doors: 4,
      exchange: true,
      financing: true,
      warranty: false,
      oneOwner: false,
      blindado: false,
      features: ["tração 4x4", "som premium", "câmera de ré", "sensor dianteiro"],
    },
  },
  {
    id: "veh-005",
    slug: "onix-plus-2023",
    name: "Onix Plus 2023",
    companySlug: "prime-motors",
    companyName: "Prime Motors",
    segment: "veiculos",
    status: "ativo",
    price: 89900,
    description: "Sedan econômico com conectividade e manutenção acessível.",
    highlights: ["sedan", "flex", "automático"],
    galleryTone: "linear-gradient(135deg, #8da6ff, #33406d)",
    details: {
      brand: "Chevrolet",
      model: "Onix Plus",
      version: "LTZ",
      year: 2023,
      modelYear: 2023,
      mileage: 15890,
      gearbox: "automatico",
      fuel: "flex",
      body: "sedan",
      color: "Branco",
      doors: 4,
      exchange: true,
      financing: true,
      warranty: true,
      oneOwner: true,
      blindado: false,
      features: ["wifi onboard", "multimídia", "rodas de liga", "espelhamento celular"],
    },
  },
  {
    id: "veh-006",
    slug: "t-cross-highline-2024",
    name: "T-Cross Highline 2024",
    companySlug: "prime-motors",
    companyName: "Prime Motors",
    segment: "veiculos",
    status: "ativo",
    price: 148900,
    description: "SUV compacto com pacote topo de linha e excelente uso urbano.",
    highlights: ["SUV", "cvt", "teto solar"],
    galleryTone: "linear-gradient(135deg, #74f1c7, #1b3227)",
    details: {
      brand: "Volkswagen",
      model: "T-Cross",
      version: "Highline",
      year: 2024,
      modelYear: 2024,
      mileage: 10120,
      gearbox: "cvt",
      fuel: "flex",
      body: "suv",
      color: "Azul",
      doors: 4,
      exchange: false,
      financing: true,
      warranty: true,
      oneOwner: true,
      blindado: false,
      features: ["teto solar", "painel digital", "piloto adaptativo", "chave presencial"],
    },
  },
  {
    id: "veh-007",
    slug: "civic-touring-2022",
    name: "Civic Touring 2022",
    companySlug: "prime-motors",
    companyName: "Prime Motors",
    segment: "veiculos",
    status: "ativo",
    price: 162900,
    description: "Sedan premium com acabamento refinado e desempenho superior.",
    highlights: ["gasolina", "automático", "premium"],
    galleryTone: "linear-gradient(135deg, #ffb86b, #6d4212)",
    details: {
      brand: "Honda",
      model: "Civic",
      version: "Touring",
      year: 2022,
      modelYear: 2022,
      mileage: 22840,
      gearbox: "automatico",
      fuel: "gasolina",
      body: "sedan",
      color: "Cinza",
      doors: 4,
      exchange: true,
      financing: true,
      warranty: false,
      oneOwner: true,
      blindado: false,
      features: ["câmbio CVT", "som premium", "bancos em couro", "ar dual zone"],
    },
  },
  {
    id: "veh-008",
    slug: "hilux-srx-2021",
    name: "Hilux SRX 2021",
    companySlug: "prime-motors",
    companyName: "Prime Motors",
    segment: "veiculos",
    status: "ativo",
    price: 214900,
    description: "Picape robusta com conforto de SUV e reputação de resistência.",
    highlights: ["picape", "diesel", "luxo"],
    galleryTone: "linear-gradient(135deg, #8da6ff, #253b68)",
    details: {
      brand: "Toyota",
      model: "Hilux",
      version: "SRX",
      year: 2021,
      modelYear: 2021,
      mileage: 54800,
      gearbox: "automatico",
      fuel: "diesel",
      body: "picape",
      color: "Prata",
      doors: 4,
      exchange: true,
      financing: true,
      warranty: false,
      oneOwner: false,
      blindado: false,
      features: ["4x4", "capota marítima", "multimídia", "sensor de ponto cego"],
    },
  },
  {
    id: "veh-009",
    slug: "kwid-zen-2024",
    name: "Kwid Zen 2024",
    companySlug: "prime-motors",
    companyName: "Prime Motors",
    segment: "veiculos",
    status: "ativo",
    price: 69900,
    description: "Hatch econômico para uso urbano com custo de entrada baixo.",
    highlights: ["hatch", "flex", "manual"],
    galleryTone: "linear-gradient(135deg, #74f1c7, #173f31)",
    details: {
      brand: "Renault",
      model: "Kwid",
      version: "Zen",
      year: 2024,
      modelYear: 2024,
      mileage: 3600,
      gearbox: "manual",
      fuel: "flex",
      body: "hatch",
      color: "Laranja",
      doors: 4,
      exchange: true,
      financing: true,
      warranty: true,
      oneOwner: true,
      blindado: false,
      features: ["central multimídia", "sensor de ré", "airbag duplo", "direção elétrica"],
    },
  },
  {
    id: "veh-010",
    slug: "compass-limited-2023",
    name: "Compass Limited 2023",
    companySlug: "prime-motors",
    companyName: "Prime Motors",
    segment: "veiculos",
    status: "ativo",
    price: 173900,
    description: "SUV com design marcante e pacote completo de conforto e tecnologia.",
    highlights: ["SUV", "automático", "flex"],
    galleryTone: "linear-gradient(135deg, #ff6f91, #401625)",
    details: {
      brand: "Jeep",
      model: "Compass",
      version: "Limited",
      year: 2023,
      modelYear: 2023,
      mileage: 19740,
      gearbox: "automatico",
      fuel: "flex",
      body: "suv",
      color: "Branco",
      doors: 4,
      exchange: true,
      financing: true,
      warranty: true,
      oneOwner: true,
      blindado: false,
      features: ["faróis full led", "teto panorâmico", "banco elétrico", "porta-malas elétrico"],
    },
  },
];

const productItems: CatalogItem[] = [
  {
    id: "prd-001",
    slug: "camiseta-essential",
    name: "Camiseta Essential",
    companySlug: "urban-store",
    companyName: "Urban Store",
    segment: "ecommerce",
    status: "ativo",
    price: 89.9,
    description: "Camiseta premium em algodão com caimento reto e toque macio.",
    highlights: ["algodão", "unissex", "3 cores"],
    galleryTone: "linear-gradient(135deg, #74f1c7, #1a3e34)",
    featured: true,
    details: {
      sku: "UST-CAM-001",
      brand: "Urban Studio",
      category: "Moda",
      subcategory: "Camisetas",
      color: "Preto",
      size: "M",
      material: "Algodão premium",
      stock: 11,
      warrantyMonths: 3,
      features: ["modelagem reta", "gola reforçada", "tecido respirável"],
      variants: [
        { label: "Preto P", value: "preto-p", stock: 3, price: 89.9 },
        { label: "Preto M", value: "preto-m", stock: 8, price: 89.9 },
        { label: "Preto G", value: "preto-g", stock: 0, price: 89.9 },
        { label: "Branco M", value: "branco-m", stock: 5, price: 89.9 },
      ],
    },
  },
  {
    id: "prd-002",
    slug: "tenis-run-core",
    name: "Tênis Run Core",
    companySlug: "urban-store",
    companyName: "Urban Store",
    segment: "ecommerce",
    status: "ativo",
    price: 279.9,
    description: "Tênis leve para treino e rotina urbana, com amortecimento estável.",
    highlights: ["38 ao 43", "leve", "cinza/preto"],
    galleryTone: "linear-gradient(135deg, #8da6ff, #263d71)",
    details: {
      sku: "UST-TEN-014",
      brand: "Urban Motion",
      category: "Calçados",
      subcategory: "Tênis",
      color: "Cinza",
      size: "41",
      material: "Mesh e borracha",
      stock: 18,
      warrantyMonths: 6,
      features: ["amortecimento", "solado aderente", "respirável"],
      variants: [
        { label: "Preto 40", value: "preto-40", stock: 4, price: 279.9 },
        { label: "Preto 41", value: "preto-41", stock: 2, price: 279.9 },
        { label: "Cinza 42", value: "cinza-42", stock: 6, price: 279.9 },
      ],
    },
  },
  {
    id: "prd-003",
    slug: "notebook-atlas-15",
    name: "Notebook Atlas 15",
    companySlug: "urban-store",
    companyName: "Urban Store",
    segment: "ecommerce",
    status: "ativo",
    price: 4999,
    description: "Notebook intermediário com SSD rápido e foco em produtividade.",
    highlights: ["16 GB", "512 GB SSD", "15.6\""],
    galleryTone: "linear-gradient(135deg, #ffb86b, #5c3612)",
    details: {
      sku: "UST-NBK-120",
      brand: "Atlas",
      category: "Eletrônicos",
      subcategory: "Notebooks",
      color: "Cinza",
      size: "15.6",
      material: "Alumínio e policarbonato",
      stock: 6,
      warrantyMonths: 12,
      features: ["Intel i5", "16 GB RAM", "SSD 512 GB", "teclado retroiluminado"],
      variants: [
        { label: "16 GB / 512 GB", value: "16-512", stock: 6, price: 4999 },
        { label: "8 GB / 256 GB", value: "8-256", stock: 2, price: 4399 },
      ],
    },
  },
  {
    id: "prd-004",
    slug: "fone-pulse-pro",
    name: "Fone Pulse Pro",
    companySlug: "urban-store",
    companyName: "Urban Store",
    segment: "ecommerce",
    status: "ativo",
    price: 349,
    description: "Fone sem fio com cancelamento de ruído e estojo de carregamento.",
    highlights: ["bluetooth", "ANC", "até 28h"],
    galleryTone: "linear-gradient(135deg, #74f1c7, #194d42)",
    details: {
      sku: "UST-FNE-033",
      brand: "Pulse",
      category: "Eletrônicos",
      subcategory: "Fones",
      color: "Preto",
      size: "Único",
      material: "Plástico ABS",
      stock: 22,
      warrantyMonths: 12,
      features: ["cancelamento de ruído", "microfone duplo", "carga rápida"],
      variants: [
        { label: "Preto", value: "preto", stock: 14, price: 349 },
        { label: "Azul", value: "azul", stock: 8, price: 349 },
      ],
    },
  },
  {
    id: "prd-005",
    slug: "mochila-urban-pack",
    name: "Mochila Urban Pack",
    companySlug: "urban-store",
    companyName: "Urban Store",
    segment: "ecommerce",
    status: "ativo",
    price: 219.9,
    description: "Mochila urbana resistente com compartimento para notebook.",
    highlights: ["21L", "notebook 15\"", "resistente"],
    galleryTone: "linear-gradient(135deg, #8da6ff, #1f2744)",
    details: {
      sku: "UST-MCH-008",
      brand: "Urban Move",
      category: "Acessórios",
      subcategory: "Mochilas",
      color: "Grafite",
      size: "Único",
      material: "Poliéster",
      stock: 17,
      warrantyMonths: 6,
      features: ["impermeável", "porta USB", "bolso antifurto"],
      variants: [
        { label: "Grafite", value: "grafite", stock: 17, price: 219.9 },
        { label: "Preta", value: "preta", stock: 7, price: 219.9 },
      ],
    },
  },
  {
    id: "prd-006",
    slug: "cadeira-ergo-work",
    name: "Cadeira Ergo Work",
    companySlug: "urban-store",
    companyName: "Urban Store",
    segment: "ecommerce",
    status: "ativo",
    price: 1299,
    description: "Cadeira ergonômica com apoio lombar e ajustes múltiplos.",
    highlights: ["ergonômica", "apoio lombar", "rodízios"],
    galleryTone: "linear-gradient(135deg, #ff6f91, #4b1e2f)",
    details: {
      sku: "UST-CRD-011",
      brand: "Ergo Lab",
      category: "Casa e Escritório",
      subcategory: "Cadeiras",
      color: "Preto",
      size: "Único",
      material: "Tela mesh e nylon",
      stock: 5,
      warrantyMonths: 12,
      features: ["inclinação ajustável", "braços reguláveis", "base cromada"],
      variants: [
        { label: "Preta", value: "preta", stock: 5, price: 1299 },
        { label: "Cinza", value: "cinza", stock: 2, price: 1299 },
      ],
    },
  },
  {
    id: "prd-007",
    slug: "cafeteira-aroma-duo",
    name: "Cafeteira Aroma Duo",
    companySlug: "urban-store",
    companyName: "Urban Store",
    segment: "ecommerce",
    status: "ativo",
    price: 399,
    description: "Cafeteira compacta para casa e escritório, com programação simples.",
    highlights: ["1,2L", "programável", "inox"],
    galleryTone: "linear-gradient(135deg, #ffb86b, #6b430f)",
    details: {
      sku: "UST-CFT-022",
      brand: "Aroma",
      category: "Casa",
      subcategory: "Cafeteiras",
      color: "Prata",
      size: "Único",
      material: "Inox e plástico",
      stock: 8,
      warrantyMonths: 12,
      features: ["desligamento automático", "filtro removível", "aquecimento rápido"],
      variants: [
        { label: "Prata", value: "prata", stock: 8, price: 399 },
        { label: "Preta", value: "preta", stock: 3, price: 399 },
      ],
    },
  },
  {
    id: "prd-008",
    slug: "relogio-pulse-one",
    name: "Relógio Pulse One",
    companySlug: "urban-store",
    companyName: "Urban Store",
    segment: "ecommerce",
    status: "ativo",
    price: 499,
    description: "Relógio casual com pulseira intercambiável e resistência à água.",
    highlights: ["resistente à água", "pulseira extra", "smart casual"],
    galleryTone: "linear-gradient(135deg, #74f1c7, #163b35)",
    details: {
      sku: "UST-RLG-007",
      brand: "Pulse",
      category: "Acessórios",
      subcategory: "Relógios",
      color: "Preto",
      size: "Único",
      material: "Aço e silicone",
      stock: 13,
      warrantyMonths: 12,
      features: ["resistência 5ATM", "visor analógico", "pulseira extra"],
      variants: [
        { label: "Preto", value: "preto", stock: 6, price: 499 },
        { label: "Marrom", value: "marrom", stock: 7, price: 499 },
      ],
    },
  },
  {
    id: "prd-009",
    slug: "jaqueta-storm-shell",
    name: "Jaqueta Storm Shell",
    companySlug: "urban-store",
    companyName: "Urban Store",
    segment: "ecommerce",
    status: "ativo",
    price: 329.9,
    description: "Jaqueta leve corta-vento com tecido técnico e acabamento clean.",
    highlights: ["corta-vento", "P ao GG", "2 cores"],
    galleryTone: "linear-gradient(135deg, #8da6ff, #273151)",
    details: {
      sku: "UST-JKT-044",
      brand: "Urban Trail",
      category: "Moda",
      subcategory: "Jaquetas",
      color: "Preto",
      size: "M",
      material: "Poliéster técnico",
      stock: 9,
      warrantyMonths: 3,
      features: ["ziper impermeável", "capuz removível", "secagem rápida"],
      variants: [
        { label: "Preto M", value: "preto-m", stock: 4, price: 329.9 },
        { label: "Preto G", value: "preto-g", stock: 0, price: 329.9 },
        { label: "Cinza M", value: "cinza-m", stock: 5, price: 329.9 },
      ],
    },
  },
  {
    id: "prd-010",
    slug: "smartwatch-flex-2",
    name: "Smartwatch Flex 2",
    companySlug: "urban-store",
    companyName: "Urban Store",
    segment: "ecommerce",
    status: "ativo",
    price: 699,
    description: "Smartwatch com monitoramento de saúde e múltiplos perfis esportivos.",
    highlights: ["GPS", "batimentos", "7 dias"],
    galleryTone: "linear-gradient(135deg, #ff6f91, #4b1727)",
    details: {
      sku: "UST-SMW-012",
      brand: "Flex",
      category: "Eletrônicos",
      subcategory: "Wearables",
      color: "Grafite",
      size: "Único",
      material: "Alumínio e silicone",
      stock: 14,
      warrantyMonths: 12,
      features: ["oxímetro", "GPS", "monitor cardíaco", "múltiplos mostradores"],
      variants: [
        { label: "Grafite", value: "grafite", stock: 14, price: 699 },
        { label: "Rose", value: "rose", stock: 6, price: 699 },
      ],
    },
  },
];

const foodItems: CatalogItem[] = [
  {
    id: "food-001",
    slug: "pizza-calabresa",
    name: "Pizza Calabresa",
    companySlug: "pizza-bella",
    companyName: "Pizza Bella",
    segment: "food",
    status: "ativo",
    price: 49.9,
    description: "Pizza clássica com molho artesanal, calabresa e borda opcional.",
    highlights: ["até 4 pessoas", "sem cebola opcional", "3 tamanhos"],
    galleryTone: "linear-gradient(135deg, #ff6f91, #5b2235)",
    featured: true,
    details: {
      category: "Pizzas",
      serves: 4,
      prepTime: 25,
      ingredients: ["molho artesanal", "muçarela", "calabresa", "orégano"],
      allergens: ["glúten", "lactose"],
      removals: ["cebola", "azeitona"],
      addOns: [
        { label: "Bacon", price: 8 },
        { label: "Catupiry", price: 7 },
        { label: "Borda recheada", price: 12 },
      ],
      sizes: [
        { label: "Pequena", price: 39.9 },
        { label: "Média", price: 49.9 },
        { label: "Grande", price: 59.9 },
      ],
    },
  },
  {
    id: "food-002",
    slug: "pizza-margherita",
    name: "Pizza Margherita",
    companySlug: "pizza-bella",
    companyName: "Pizza Bella",
    segment: "food",
    status: "ativo",
    price: 46.9,
    description: "Pizza leve com molho, muçarela, tomate e manjericão fresco.",
    highlights: ["vegetariana", "leve", "sem carne"],
    galleryTone: "linear-gradient(135deg, #74f1c7, #16423e)",
    details: {
      category: "Pizzas",
      serves: 4,
      prepTime: 20,
      ingredients: ["molho artesanal", "muçarela", "tomate", "manjericão"],
      allergens: ["glúten", "lactose"],
      removals: ["tomate", "manjericão"],
      addOns: [
        { label: "Borda recheada", price: 12 },
        { label: "Azeitona extra", price: 4 },
      ],
      sizes: [
        { label: "Pequena", price: 36.9 },
        { label: "Média", price: 46.9 },
        { label: "Grande", price: 56.9 },
      ],
    },
  },
  {
    id: "food-003",
    slug: "burger-prime-bacon",
    name: "Burger Prime Bacon",
    companySlug: "pizza-bella",
    companyName: "Pizza Bella",
    segment: "food",
    status: "ativo",
    price: 34.9,
    description: "Burger suculento com bacon crocante e molho da casa.",
    highlights: ["com bacon", "combo opcional", "pronto rápido"],
    galleryTone: "linear-gradient(135deg, #ffb86b, #63380f)",
    details: {
      category: "Burgers",
      serves: 1,
      prepTime: 15,
      ingredients: ["pão brioche", "hambúrguer bovino", "bacon", "queijo prato"],
      allergens: ["glúten", "lactose", "ovos"],
      removals: ["cebola", "picles"],
      addOns: [
        { label: "Batata", price: 10 },
        { label: "Cheddar", price: 6 },
      ],
      sizes: [
        { label: "Individual", price: 34.9 },
        { label: "Combo", price: 49.9 },
      ],
    },
  },
  {
    id: "food-004",
    slug: "burger-veg",
    name: "Burger Veg",
    companySlug: "pizza-bella",
    companyName: "Pizza Bella",
    segment: "food",
    status: "ativo",
    price: 31.9,
    description: "Burger vegetal com vegetais grelhados e molho de ervas.",
    highlights: ["vegetariano", "sem carne", "leve"],
    galleryTone: "linear-gradient(135deg, #6fca87, #19412e)",
    details: {
      category: "Burgers",
      serves: 1,
      prepTime: 14,
      ingredients: ["pão integral", "hambúrguer vegetal", "alface", "tomate", "molho de ervas"],
      allergens: ["glúten"],
      removals: ["cebola", "molho de ervas"],
      addOns: [
        { label: "Queijo vegano", price: 7 },
        { label: "Batata doce", price: 11 },
      ],
      sizes: [
        { label: "Individual", price: 31.9 },
      ],
    },
  },
  {
    id: "food-005",
    slug: "poke-salmon",
    name: "Poke Salmon",
    companySlug: "pizza-bella",
    companyName: "Pizza Bella",
    segment: "food",
    status: "ativo",
    price: 42.9,
    description: "Poke fresco com salmão, arroz japonês e legumes crocantes.",
    highlights: ["saudável", "1 pessoa", "sem lactose"],
    galleryTone: "linear-gradient(135deg, #8da6ff, #243566)",
    details: {
      category: "Bowls",
      serves: 1,
      prepTime: 12,
      ingredients: ["arroz japonês", "salmão", "edamame", "pepino", "manga"],
      allergens: ["peixe", "soja"],
      removals: ["manga", "pepino"],
      addOns: [
        { label: "Cream cheese", price: 5 },
        { label: "Tobiko", price: 9 },
      ],
      sizes: [
        { label: "Padrão", price: 42.9 },
        { label: "Plus", price: 54.9 },
      ],
    },
  },
  {
    id: "food-006",
    slug: "frango-crispy-box",
    name: "Frango Crispy Box",
    companySlug: "pizza-bella",
    companyName: "Pizza Bella",
    segment: "food",
    status: "ativo",
    price: 39.9,
    description: "Porção crocante com frango, molhos e batata para compartilhar.",
    highlights: ["serve 2", "crocante", "molhos"],
    galleryTone: "linear-gradient(135deg, #ff6f91, #4c1f2e)",
    details: {
      category: "Porções",
      serves: 2,
      prepTime: 18,
      ingredients: ["frango empanado", "batata", "molho barbecue", "molho cheddar"],
      allergens: ["glúten", "lactose", "ovos"],
      removals: ["pimenta"],
      addOns: [
        { label: "Molho extra", price: 4 },
        { label: "Batata extra", price: 8 },
      ],
      sizes: [
        { label: "Box", price: 39.9 },
        { label: "Combo", price: 52.9 },
      ],
    },
  },
  {
    id: "food-007",
    slug: "prato-executivo-bife",
    name: "Prato Executivo Bife",
    companySlug: "pizza-bella",
    companyName: "Pizza Bella",
    segment: "food",
    status: "ativo",
    price: 36.9,
    description: "Prato executivo completo com arroz, feijão, bife e salada.",
    highlights: ["serve 1", "tradicional", "rápido"],
    galleryTone: "linear-gradient(135deg, #74f1c7, #1b463f)",
    details: {
      category: "Pratos",
      serves: 1,
      prepTime: 16,
      ingredients: ["arroz", "feijão", "bife", "salada", "farofa"],
      allergens: ["glúten"],
      removals: ["farofa", "salada"],
      addOns: [
        { label: "Ovo", price: 4 },
        { label: "Suco", price: 7 },
      ],
      sizes: [
        { label: "Executivo", price: 36.9 },
      ],
    },
  },
  {
    id: "food-008",
    slug: "salada-fit-bowl",
    name: "Salada Fit Bowl",
    companySlug: "pizza-bella",
    companyName: "Pizza Bella",
    segment: "food",
    status: "ativo",
    price: 28.9,
    description: "Bowl leve com folhas, grãos, proteínas e molho cítrico.",
    highlights: ["fit", "leve", "sem lactose"],
    galleryTone: "linear-gradient(135deg, #6fca87, #183924)",
    details: {
      category: "Saladas",
      serves: 1,
      prepTime: 10,
      ingredients: ["alface", "rúcula", "grão-de-bico", "tomate cereja", "frango grelhado"],
      allergens: ["soja"],
      removals: ["frango", "molho cítrico"],
      addOns: [
        { label: "Quinoa", price: 6 },
        { label: "Abacate", price: 8 },
      ],
      sizes: [
        { label: "Bowl", price: 28.9 },
      ],
    },
  },
  {
    id: "food-009",
    slug: "brownie-duplo",
    name: "Brownie Duplo",
    companySlug: "pizza-bella",
    companyName: "Pizza Bella",
    segment: "food",
    status: "ativo",
    price: 18.9,
    description: "Sobremesa intensa com chocolate e calda opcional.",
    highlights: ["sobremesa", "chocolate", "individual"],
    galleryTone: "linear-gradient(135deg, #ffb86b, #5d330f)",
    details: {
      category: "Sobremesas",
      serves: 1,
      prepTime: 8,
      ingredients: ["chocolate meio amargo", "manteiga", "farinha", "cacau"],
      allergens: ["glúten", "lactose", "ovos"],
      removals: ["calda"],
      addOns: [
        { label: "Sorvete", price: 7 },
        { label: "Calda extra", price: 3 },
      ],
      sizes: [
        { label: "Individual", price: 18.9 },
      ],
    },
  },
  {
    id: "food-010",
    slug: "refrigerante-craft-lemon",
    name: "Refrigerante Craft Lemon",
    companySlug: "pizza-bella",
    companyName: "Pizza Bella",
    segment: "food",
    status: "ativo",
    price: 9.9,
    description: "Bebida artesanal de limão, gelada e com baixo teor de açúcar.",
    highlights: ["bebida", "gelada", "copo 300 ml"],
    galleryTone: "linear-gradient(135deg, #8da6ff, #22345e)",
    details: {
      category: "Bebidas",
      serves: 1,
      prepTime: 3,
      ingredients: ["água com gás", "limão siciliano", "xarope artesanal"],
      allergens: [],
      removals: ["gelo"],
      addOns: [
        { label: "Gelo extra", price: 0 },
      ],
      sizes: [
        { label: "300 ml", price: 9.9 },
        { label: "500 ml", price: 12.9 },
      ],
    },
  },
];

export const catalogItems: CatalogItem[] = [
  ...propertyItems,
  ...vehicleItems,
  ...productItems,
  ...foodItems,
];
